# Generated by Django 5.1.1 on 2024-09-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0004_contact_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='user',
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
